### ISSUE TITLE
Cannot receive messages longer then 124 characters

### ISSUE THREAD

**Issue by DigitalVS** [Molorius/esp32-websocket#17]
Hello!
On the project homepage, you say that size of the messages are limited only by available memory but I can receive only messages long up to 124 characters (?!?). It can send longer messages but cannot receive them.
Did you ever tried longer messages?

**Comment by Molorius** [comment]
I have not seen any problems sending or receiving any size of packet ever since commit 88e15394f51cba72790b2061c80fd7b6ee76249d. I just updated [the example](https://github.com/Molorius/ESP32-Examples/tree/master/websocket_server) so you can easily send any message to the esp32; it can successfully receive a message with 1000+ characters. 

Do you have example code of when it is not working? I would like to fix it if it's still a problem.

**Comment by DigitalVS** [comment]
Yes, you are right, with that commit it is working correctly.
It's mystery how come that I know for your project only for 3 months but I didn't have changes old 13 months, but anyway, this is not a bug now and I am thus closing this issue!
Thank you for your cooperation!
