### ISSUE TITLE
unnecessary modifiable char*

### ISSUE THREAD

**Issue by yzazik** [Molorius/esp32-websocket#22]
Great component, helps a lot.
It would be great if most of the char* in functions parameters would have const modifier to avoid unnecessary conversion to writable buffers when it is not in fact needed.
Thank you.

**Comment by Molorius** [comment]
These functions take in pointers to underlying arrays, not the arrays themselves. Typecasting any pointer to another doesn't take much cpu time at all since it is only modifying the pointer, not the data being pointed to. 

Additionally, it is my understanding that a const modifier is a compile-time check in C, not a run-time conversion. I haven't looked too much into how gcc does this for xtensa architecture so I could be wrong on that for the esp32. This stackoverflow question seems to agree with me: https://stackoverflow.com/questions/7715371/whats-the-point-of-const-pointers

Please respond if you have additional problems, I'll close this in a few days if not.
